### ISSUE TITLE
can not receive can data when dlc < 8

### ISSUE THREAD

**Issue by chenzhengxi** [autowarefoundation/ros2_socketcan#14]
`    const auto ret = receive(&data_raw[0U], timeout);
    if (ret.length() != sizeof(data)) {
      throw std::runtime_error{"Received CAN data is of size incompatible with provided type!"};
    }
`
if can data length < 8, it will throw error

**Comment by JWhitleyWork** [comment]
Coould you please link to the line in the code where this exists? I'm not sure that this means what you think it means.
