### ISSUE TITLE
Missing header file

### ISSUE THREAD

**Issue by TheLisiak** [autowarefoundation/ros2_socketcan#47]
![Screenshot from 2024-05-14 16-40-54](https://github.com/autowarefoundation/ros2_socketcan/assets/92057427/4322a61c-3084-4cf2-b837-a51b23cec7f1)
I can not build a package because of this error. I tried to update the dependencies via rosdep, but did not help.

ROS2 Humble
Ubuntu 22.04

**Comment by TheLisiak** [comment]
I solve it. I found the solution in this post: https://answers.ros.org/question/375690/fatal-error-can_msgsmsgframehpp-no-such-file-or-directory/

At the time of creating the issue ticket, [ros answers ](https://answers.ros.org/) were unavailable for some technical problem. For the future, I am adding a transcript of the answer.

You need to install the can_msgs package to your ros workspace.

`sudo apt install ros-$ROS_DISTRO-can-msgs`

`source /opt/ros/$ROS_DISTRO/setup.bash`

Make sure to clean up your local ros workspace (i.e. remove build/ install/ log/) before `colcon build`.

To see all the packages you have installed to your machine:

ls `/opt/ros/$ROS_DISTRO/include/` and ls `/opt/ros/$ROS_DISTRO/share`.

Another comment suggesting this:

I encountered the same issue when trying to build the ros2_socketcan. 
Manually adding find_package(can_msgs REQUIRED) to the CMake list of the package solved the issue for me (Ubuntu 22.04, ROS Humble Desktop Docker).

**Comment by JWhitleyWork** [comment]
For anyone else encountering this issue, please see [this article](https://docs.ros.org/en/humble/Tutorials/Intermediate/Rosdep.html#how-do-i-use-the-rosdep-tool) on how to use the `rosdep` tool to automatically install dependencies for packages being built from source.
