### ISSUE TITLE
How to getting started with ros2_socketcan?

### ISSUE THREAD

**Issue by Caracal117** [autowarefoundation/ros2_socketcan#51]
Hi, I'm new to both ROS2 and Socketcan. I'm trying to use this package, built from source in ROS humble, but with the command of 
`ros2 launch socket_can_bridge.launch.xml`, the terminal output turns out to be
![Screenshot from 2024-07-19 15-24-36](https://github.com/user-attachments/assets/646fccbe-5951-4240-b3c8-2e16fc66c4b9)
In my system, I'm able to use can-utils to send out some simple message. 
![Screenshot from 2024-07-19 15-57-53](https://github.com/user-attachments/assets/edbd04ff-dad1-4e00-9641-41f568434e9a)

Am i missing some configuration step, could you help me use this package? Thanks in advance.

**Comment by anandadio** [comment]
Any updates? i'm having the same issue

**Comment by tonynajjar** [comment]
Are you getting seeing data on the receiving topic? If yes then the timeouts are probably nothing to worry about. It's likely that you just don't send data fast enough on the canbus. You can confirm this by sending data at a higher rate and see if the timeout goes away, e.g. `cangen can0 -g 1 -I 123 -L 8 -D i`. If that's the issue then you can "supress" the warning by increasing the "receiver_interval_sec"
