### ISSUE TITLE
ros2_socketcan and docker

### ISSUE THREAD

**Issue by ViaudJV** [autowarefoundation/ros2_socketcan#53]
Hi,
I try to used ros2_socketcan in docker.
I test candump in my computer outside docker and I receive my data.
but when i use ros2_socketcan in the docker, the node start and connect with can0 but nothing happen.  
![Screenshot from 2024-09-20 16-52-21](https://github.com/user-attachments/assets/409407a9-0035-4ced-b7d3-f397859637cc)

My docker option use network=host

what I missed?

sorry, I'm french guy.

**Comment by JWhitleyWork** [comment]
@ViaudJV Please try to use `candump` inside your Docker container to test receiving messages. If you are able to see the messages with `candump` inside the container but `socket_can_receiver` does not receive any messages then we can troubleshoot further but if `candump` inside the container can not receive messages then there is a problem with the container configuration.

**Comment by ViaudJV** [comment]
thanks, i finally the found the issue.
