### ISSUE TITLE
Missing header for fd_can

### ISSUE THREAD

**Issue by DavidKHG** [autowarefoundation/ros2_socketcan#55]
Hello everyone,
I currently have a problem with build and installing ros2_socketcan package.

![Screenshot from 2024-11-19 09-10-30](https://github.com/user-attachments/assets/cfafcbaa-19c4-40f3-9f38-fa7ba7b8619d)

- ROS Humble
- Linux 22.04.1

It shows missing header of  "ros2_socketcan_msgs/msg/fd_frame.hpp", but I don`t know where to find it.

If there exists other solution, please let me know.

Thanks.

**Comment by JWhitleyWork** [comment]
@DavidKHG You are running `colcon build` in the wrong folder. Your ROS workspace layout should look like this:

```
- workspace
  - src
    - ros2_socketcan (this repository)
      - ros2_socketcan
      - ros2_socketcan_msgs
```

And you should run `colcon build` in the `workspace` folder. This will resolve the issue.
